### ISSUE TITLE
Review of new theme implementation

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#102]
**Cover**

- [x] Have Ramon specify what should go in the cover background when no image is present. I'd like it to be something that people will feel good about, but I'm guessing he probably wouldn't use the gradient with pattern overlay that's there now.
- [x] When I try adding an image `image: graph.jpg` it overflows the box and pushes the title box into a different area of the page.
- [x] I don't think the down arrow in the circle at the bottom should be a link. Is that how Ramon spec'd it?
- [x] Instead of having a special "Contents >" button, let's just use the same "Next >" button as the other pages

**Splash Page**

- [ ] Previously, we had splash pages not as their own type of page, but rather as a class of multiple pages. Ramon's design does it differently, where a splash page is its own type. So let's establish a new `type: splash` and it's this design: http://gettylabs.org/quire/quire_starter_theme_091118_A/quire_starter_theme_primary_landing_page.html. So that we don't mess up older projects using `class: splash` we should have logic that says if type OR class are `splash` use the splash layout. But we'll deprecate the class handling and eventually remove the logic for it.

**Menu**

- [x] Intro and Main headings shouldn't be there, and nested items should be indented like the main Contents page design
- [x] Add logo (the file for which should be specified in publication.yml under publisher.logo)

**Navbar**

- [x] Is there anyway to increase the target size for the hover-over progress bar? It’s really hard to hit, even knowing it’s there. We should run this by Ramon, but maybe we could even make the target the whole navbar itself? Or at least the areas of it that aren’t already targets for the nav links and icons.

**Page types, classes, and image handling**

I’ll put this in the documentation too, but the table below shows where we should be with what page types we have, what classes those pages can have, and what to do with the image if one is supplied. Note here the new splash page, and that we should use top and side for entry page class options.

For image handling, on the content page I think it should be in the background because the design of that page is most like the cover and splash pages (it doesn't have the white content well), but check with Ramon. Also, note that for the entry page, someone should be able to use it without an object at all and instead specifying an `image`. This would put the image full width in place of the slide carousel that would be there otherwise.

Page types  | Possible classes | If `image` is specified
---- | ---- | ---- 
cover |   | in the background
splash |   | in the background
contents | grid, abstract, list*, brief | in the background (?)
page* |   | full width below title block 
entry | top*, side | full width above title block
essay |   | full width below title block 
info | about*, copyright | full width below title block 

\* = default

**Comment by naeluh** [comment]
Hi Greg!

Thanks for these items! For this one 

>  When I try adding an image image: graph.jpg it overflows the box and pushes the title box into a different area of the page.

What is image graph.jpg ?

I will let you know if I have any other questions.

Thanks!

**Comment by geealbers** [comment]
Oh, sorry. graph.jpg was just an image file that happened to be in the repo I was working in. I updated the YAML of cover.md to the below, and then saw that issue with the image going too big.

```yaml
---
title: Cover
weight: 1
menu: false
type: cover
image: graph.jpg
slug: .
---
```

**Comment by naeluh** [comment]
No prob!

Can you screen shot what you are seeing because I added `monet.jpg` and it looked fine to me? 
Thanks!

```yaml
---
title: Cover
weight: 1
menu: false
type: cover
image: monet.jpg
slug: .
---
```

**Comment by geealbers** [comment]
Sure. Before and after below. I was working with the `quire-tester` content.

<img width="1320" alt="screen shot 2018-12-11 at 10 45 11 am" src="https://user-images.githubusercontent.com/7796401/49822399-e448c800-fd31-11e8-9be4-00015b1bd85c.png">

<img width="1320" alt="screen shot 2018-12-11 at 10 45 22 am" src="https://user-images.githubusercontent.com/7796401/49822403-e6ab2200-fd31-11e8-96a1-72e541043ade.png">

**Comment by naeluh** [comment]
Oh ok I see what you mean. Thanks!

**Comment by rtapales** [comment]
@geealbers 

GA: Have Ramon specify what should go in the cover background when no image is present. I'd like it to be something that people will feel good about, but I'm guessing he probably wouldn't use the gradient with pattern overlay that's there now.

RT: I had a placeholder from a while back that I can revisit. I think simpler is better. Assuming users will go with a generic cover, then maybe there's a way to specify a hex values since colors tend to be subjective.

GA: I don't think the down arrow in the circle at the bottom should be a link. Is that how Ramon spec'd it?

RT: You're right, I did not spec that. However, I don't see a usability issue if users perceive it as a button and have it scroll down when clicked.

**Comment by mantasandri** [comment]
Finished these & closing this out.

Per today's meeting - decided on saving the splash page type for later; keeping it as a class for now.
