### ISSUE TITLE
Including an empty caption in the q-figure shortcode should display no caption

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#103]
Even if a figure has a caption defined in the `figures.yml` file, including an empty caption attribute in the `q-figure` and `q-figure-group` shortcode as below should cause no caption to be displayed at all. Instead, the `figures.yml` caption is still being shown.

```
{{< q-figure id="1.4" caption="" >}}
```

**Comment by naeluh** [comment]
So it looks as though the check is for `caption=""` existence. Unless `caption` has a value it does not see that it is there. When you add `caption=" "` The space is considered a value and the result is an empty caption. Does that work or should we check for caption with no value? Thanks!

**Comment by geealbers** [comment]
Ah, I see. It looks like with a space though, it leaves the `<figcaption>` element there, but empty, or maybe with an invisible space in it. Ideally, there'd be no `<figcaption>` at all as might have a little height, and I'm not sure what screen readers would do with visually empty elements like that. What if we changed it to check

Could we put in logic to check if the caption is just white space, or maybe also the word "false" and if either is true, don't include a `<figcation>`? My thinking with adding the "false" option is that it's more explicit that just a space, and is consistent with Quire's other ways of not displaying things.

**Comment by geealbers** [comment]
I forgot about the other elements that might be in the `<figcaption>`. Nevermind about trying to remove it if empty, there are too maybe variables to deal with to make it worth it at this point. If you can just add the logic that if caption in the shortcode is eq to "false" do nothing, that would be great. That way people could either use false or a space to override the caption in `figures.yml`
