### ISSUE TITLE
`epub: false` doesn't take page out of table of contents

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#106]
Related to #105, in that it's also an issue with the display controls, `epub: false` correctly removes the page from the epub itself, but the link to that page in the XHTML table of contents in the book remains. In the below, example, both the French Art essay and the Contributors page should not have been included. The TOCs that are used by the reading systems (`toc.ncx`) are fine though.

<img width="518" alt="screen shot 2018-12-20 at 3 50 34 pm" src="https://user-images.githubusercontent.com/7796401/50317164-0c8da080-046f-11e9-85b8-8bbc69375535.png">

**Comment by naeluh** [comment]
@geealbers Hey so I think to get this to work `toc: false` so it looks like this 

```yml
epub: false
toc: false
```

I feel that is right since you want both out of the epub and the toc?

Let me know if that works?

Thanks!

**Comment by geealbers** [comment]
The trick is that `toc: false` removes it from the online TOC as well, and that wouldn't be the desired behavior. `toc: false` is supposed to be just for making the TOC look right. There are often pages in these online publications you wouldn't want listed as their own items in the TOC. I see now that the wording is weird though.

**Comment by naeluh** [comment]
Hi @geealbers 

`toc: false`

- removes page from table of contents only

`epub: false` 

- removes page from epub but does not remove page from table of contents

`pdf: false`

- removes page from pdf but does not remove page from table of contents

`menu: false`

- removes page from menu only

Is that correct?
