### ISSUE TITLE
New Theme: Figures

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#108]
I'm really loving how the modal and the entry page viewers are looking and operating. This is leaps ahead of where we've been in previous templates or publications. The list below is long but is mostly minor buggy things, rationalizing some of the naming and logic, and changing things that I made the wrong decisions on initially but didn't see until we got this far. 😬Let me know if you have questions.

**Bugs**

- [x] The q-figure shortcode apparently now requires a `media_type` to *always* be indicated, even for regular, static figure images. This shouldn't be the case. It should work fine to include no `media_type` at all for regular figure images.

- [x] When using a figure with a `media_type: website`, the resulting iframe probably needs to be wrapped in a div with `class="quire-figure__media-wrapper--standard"`. Without that wrapper, it is absolute positioned and fills the entire content well. It's wrapped in one part of the `q-figure.html` but not everywhere.

- [x] In config.yml, if you set both `figureEnlargeType: inside` and `figureLabels: false` the expander icon shows up both on the image AND below it. It should not show below.

- [x] If you have `popup: false`, `figureEnlargeType: inside` doesn’t work, the labels remain outside. They should be inside but without the enlarge icon

- [x] I think this is because they're part of the click target for the modal, but the figure captions should be copy and paste-able. 

- [x] In Firefox, the forward and back arrows in the image viewer on the entry pages aren't clickable.

- [x] Also on the entry page figures, the z-index for some of the elements need to be adjusted as they appear over the navbar when scrolling.

**Audio and video figures**

- [x] I was wrong about not adding Soundcloud figures to the modal. It feels awkward to have those audio embeds directly in the text and not in the modal, but to have video embeds represented by a static image and only playable in the modal. My preference would be to have both of them show up as embeds directly in the text (no static image), and then to have the enlarge icon and figure label be the link to open them in the modal. And then in the modal they should show up in the carousel with the rest of the figures. All that said, I think there was maybe some issue with adding them to the modal in the first place? In which case, let's chat.

**Labels**

- [x] I'd like to move away from the auto-generated figure labels. I think that was a mistake on my part. `label`, `credit` and `caption` should all behave the same. If text for one of them is in figures.yml use it, if not leave blank. If text is included in the shortcode itself it overrides whatever is in figures.yml. If it is included in the shortcode itself, but the value is a single space or is "false", then it is made blank even if there is text for it in figures.yml.

    In a figure group, if text for one is included in the shortcode, any corresponding text in figures.yml is ignored, and the shortcode text is included as part of the group caption below all the images. Like for single figures, if the text in the shortcode is a single space or "false", this it is made blank.

**Config naming** 

- [x] With the above change, we can then eliminate the `figureLabels`, `figureLabelsTextBefore` and `figureLabelsTextAfter` parameters from config.yml along with any associated logic in the templates.

- [x]  I'd also like to rationalize some of the naming of params we’re using in config.yml. And instead of inside and outside for the label location values, I think "below" and "on-top" make a little more sense, with below being the default I guess.

    ```
    figureEnlargeType         --> figureLabelLocation: below | on-top
    figureLabels              --> remove
    figureLabelsTextBefore    --> remove
    figureLabelsTextAfter     --> remove
    popup                     --> figureModal: true | false
    
    objectLinkText            --> entryPageObjectLinkText: "View in Collection"
    catalogueFiguresZoom      --> entryPageFigureZoom: true | false
    sideBySideLayout          --> entryPageSideBySideLayout: true | false
    ```

- [x] And lastly to those, I'd like to add a `figureModalIcons` boolean that should be true by default, but when false it will remove/hide all the enlarging icons. I can foresee some people will want to do this.

**Zooming** 

- [x] In the Entry page viewer, I can't currently add IIIF image figures. However, once that's working, I really like that idea that with `entryPageFigureZoom: true` all the images can be zoomable, even if not IIIF.  To me this makes a lot of sense and I think will be better for readers, since finding some images zoomable and some not will feel pretty arbitrary to them. Better to have those zoom controls on everything (or nothing). Could we implement this same behavior on the modal as well? and then instead of `entryPageFigureZoom` we could just have `figureZoom` to turn it or or off globally.

**Static image fallbacks**

- [x] On the audio and video fallback images, I know you worked on them a lot, but they're just not working. Ramon's comps looks lovely in their initial perfect-circumstances rendering, but in real life (as you've been grappling with) it's a different story. I'd like us to simplify it back and consider something like the sketch below. 

    ![img_7180](https://user-images.githubusercontent.com/7796401/51146071-93356380-180a-11e9-8185-614e5404e9da.JPG)

    There would be a placeholder graphic that I think could just be simple PNGs (representing either video, audio, and website) and I'd suggest making them all at a 16:9 ratio. Under that we'd include the URL, and then under that, the caption. When users supplied their own fallback `src`, we'd use that image instead of the PNG, but would sill add the URL below it. With this we could also eliminate all the config.yml params like `videoFigureFallbackTextBefore` and `videoFigureFallbackTextAfter`, along with the associated logic in the templates. @rtapales should weigh in too, but let me know what you think.

**Comment by naeluh** [comment]
Hi @geealbers 
I am going through this list now. 

**iiif-leaflet viewer**
The json that I was working with has the same naming keys but the location of the key/value pair is different in the json that you are using we have to figure out what we want to support in terms of the manifest structure.

The json I used to test with looks like this:

```
// https://libimages.princeton.edu/loris/pudl0030/021/00000001.jp2/info.json
{
  "profile": [
    "http://iiif.io/api/image/2/level2.json",
    {
      "supports": [
        "canonicalLinkHeader",
        "profileLinkHeader",
        "mirroring",
        "rotationArbitrary",
        "regionSquare",
        "sizeAboveFull"
      ],
      "qualities": [
        "default",
        "bitonal",
        "gray",
        "color"
      ],
      "formats": [
        "jpg",
        "png",
        "gif",
        "webp"
      ]
    }
  ],
  "tiles": [{
    "width": 1024,
    "scaleFactors": [
      1,
      2,
      4,
      8,
      16,
      32,
      64,
      128
    ]
  }],
  "protocol": "http://iiif.io/api/image",
  "sizes": [{
      "width": 57,
      "height": 33
    },
    {
      "width": 113,
      "height": 65
    },
    {
      "width": 225,
      "height": 129
    },
    {
      "width": 450,
      "height": 257
    },
    {
      "width": 900,
      "height": 514
    },
    {
      "width": 1800,
      "height": 1028
    },
    {
      "width": 3600,
      "height": 2055
    },
    {
      "width": 7200,
      "height": 4110
    }
  ],
  "height": 4110,
  "width": 7200,
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "https://libimages.princeton.edu/loris/pudl0030%2F021%2F00000001.jp2"
}
```
The height and width values were nested much deeper in the json you were trying to use. We need to discuss which ones we need to support. Let me know if that makes sense. 

Thanks for the notes I will let you know if I have any questions.

**Comment by geealbers** [comment]
Thanks @naeluh. On IIIF, I think we should have a conversation with David about it. It will be critical for an upcoming pub we're working on now, but not for this next Quire release. Let's leave it working as is now (using the `info.json` link) and I'll find us a time to talk to David.

**Comment by naeluh** [comment]
Ok sounds good thanks !

**Comment by naeluh** [comment]
@geealbers hope you are having a great day!

can i get some clarification here : 

>  I think this is because they're part of the click target for the modal, but the figure captions should be copy and paste-able.

**Comment by geealbers** [comment]
Oh yes, I meant that the text in the figure captions should be selectable so that a user could copy and paste them into another document if they wanted to. As it is now, the `<figcaption>`s are inside the popup link, so when you hover over the text and try to select it to copy it, the modal opens instead. It might meaning applying a `user-select` css value to the captions, or maybe changing the the popup link to the image and figure label and icon, rather than to the whole `<figure>` block.

**Comment by naeluh** [comment]
Hi @geealbers if you pull down my last commit - the checked ones should be cleared up. 
There are some changes in the `package.json` so I would `rm -rf node_modules/` `npm install` for the theme folder. Let me know if you have any questions. Thanks!

**Comment by naeluh** [comment]
Hi @geealbers for audio, video website figures do we need to require a src or a media_id? If we have a fallback styling for no src. I am not sure this is needed as a requirement for these media_types anymore? Let me know if that makes sense. Thanks!

**Comment by geealbers** [comment]
Yes, that's right. `src` should not be required for any of those.

**Comment by naeluh** [comment]
@geealbers 

These commits https://github.com/gettypubs/quire-starter-theme/commit/80e6e5e2d83771a0ba9d861c6e305b584c741992 also https://github.com/gettypubs/quire-starter/commit/7503f4d430a3156de3a2a7bdea64fafa8db8715b address this:

> 
> I'd like to move away from the auto-generated figure labels. I think that was a mistake on my part. label, credit and caption should all behave the same. If text for one of them is in `figures.yml` use it, if not leave blank. If text is included in the shortcode itself it overrides whatever is in `figures.yml`. If it is included in the shortcode itself, but the value is a single space or is "false", then it is made blank even if there is text for it in `figures.yml`.
> 
> In a figure group, if text for one is included in the shortcode, any corresponding text in `figures.yml` is ignored, and the shortcode text is included as part of the group caption below all the images. Like for single figures, if the text in the shortcode is a single space or "false", this it is made blank.

`labels` `captions` and `credit` for `q-figure` and `q-figure-zoom `

``` yaml
figure_list:
  - id: "cat-1"
    label: "Figure 1."
    src: 04742401-detail.jpg
    media_type: image
    alt: "A house cat, walking in mid stride, in front of a gridded background"
    caption: "Eadweard J. Muybridge (American, born England, 1830–1904), *Animal Locomotion* (detail), 1887. Collotype. J. Paul Getty Museum, Los Angeles, 84.XM.628.56"
    credit: "Public domain"
```

if any of these are present in `figures.yml` they will be displayed if they are not there or empty they will not show.

The shortcode attributes will always override `figures.yml`

For `q-figure-group` shortcode caption will override the individual captions as a group caption.

The big change here is that `label="true | false"` is how to set label and `label_text=""` is gone.

Let me know if that works. 

Thanks!

**Comment by geealbers** [comment]
Yes, I think that's all it!

**Comment by naeluh** [comment]
@geealbers ok great ! thanks !

**Comment by naeluh** [comment]
@geealbers 

> In the Entry page viewer, I can't currently add IIIF image figures. However, once that's working, I really like that idea that with `entryPageFigureZoom: true` all the images can be zoomable, even if not IIIF. To me this makes a lot of sense and I think will be better for readers, since finding some images zoomable and some not will feel pretty arbitrary to them. Better to have those zoom controls on everything (or nothing). Could we implement this same behavior on the modal as well? and then instead of `entryPageFigureZoom` we could just have `figureZoom` to turn it or or off globally.

For this when a user sets `figureModal:false` should the images be an inline leaflet viewer or go to a image element or should the image element only appear when `figureModal:false` and `figureZoom:false` ?

Let me know if that makes sense. 

Thanks!

**Comment by naeluh** [comment]
@geealbers 

`figureZoom` is `true` by default and when it `false` the modal and entry just go back to the older version. 

If `figureZoom:false` and `figureModal:false` then we get inline elements.

Let me know if that works.

Thanks!
