### ISSUE TITLE
Theme Primary Normal: Update Body Font Color (global)

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#111]
Update color to a darker gray - #333333.

**Comment by mantasandri** [comment]
Updated to #333333 for primary and #000000 for secondary when background is lighter color.  When dark, updates to #ffffff.

**Comment by rtapales** [comment]
I think you missed the copy on the homepage for the Secondary Theme. That's reading as #333333.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/665ac97efabfe814690b9121ae3e83253f8bbbac and reuploaded.

**Comment by rtapales** [comment]
Verified.
