### ISSUE TITLE
Theme Primary Normal: Contents Grid

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#116]
- Tighten spacing between tiles. Looks to be around 10-12px on the design.
- For titles with images, the font is bold 18px/22px. 
- For titles without images, the font is bold 37px/45px.

**Comment by rtapales** [comment]
Section headers also need to be modified per comp.

**Comment by mantasandri** [comment]
Fixed in https://github.com/gettypubs/quire-starter-theme/commit/c226bf39ab3a590f809465196dd08ebfcd873c5c

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/8ecc966d2f24846d56b7c602e60b32aa58d29a71 and reuploaded.

**Comment by rtapales** [comment]
Verified.
