### ISSUE TITLE
Theme Primary: Tables

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#117]
- Line under <th> element should be same thickness. Right now it looks doubled.
- There should be a little (white) break in between columns
- Add line after the final row unless it's a table footer.
- Might need a little more margin after the table.

**Comment by mantasandri** [comment]
Should be fixed with https://github.com/gettypubs/quire-starter-theme/commit/cc265f6d3ed49279500d2b34a4c2ccaefe732910

**Comment by rtapales** [comment]
Verified.
