### ISSUE TITLE
Primary + Secondary Themes: Lists

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#118]
Add more space between list items - approximately 1em.

Definitions List
<dt> Make it bold.
<dd> Take out indent. Make it italic.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/407421a04c9d26cea16ba1eb6e7c0030aed7e5ad

**Comment by rtapales** [comment]
- Please add a little more space below the dd element so it creates more separation between definitions. 
- Also, the bullet ornament (ul) in the secondary theme looks really big. Please reduce to same size as the ones in the notes section.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/e39ebcf98d3a4d2844975ecbc9094c0d2663f7b8 and reuploaded.

**Comment by rtapales** [comment]
Verified.
