### ISSUE TITLE
Primary + Secondary Themes: Images

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#121]
http://gettylabs.org/quire/quire_starter_theme_010819/primary/normal/figures/

- Width of single images and image sets should fill content well - basically to align with the width of the copy.
- Take out top margin on floated images so top aligns with top of paragraph.
- Missing Fig and expand icons.

**Comment by mantasandri** [comment]
Config was set to display the figureLabelLocation to below, changed to on-top.  Fixed with: https://github.com/gettypubs/quire-starter-theme/commit/069b412191d9ac5ee87e8dfb5ab3244d9552ea7b & https://github.com/gettypubs/quire-starter-theme/commit/4a305b03ecfcecf4a6d1fc814677c6ebc2124054

**Comment by rtapales** [comment]
Verified.
