### ISSUE TITLE
Primary + Secondary Theme: Subtitle

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#122]
http://gettylabs.org/quire/quire_starter_theme_010819/primary/normal/essay/

Is there a negative letter-spacing on the copy below 'Essay?' Looks too tight. If so, can we reset to default leading?

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/4c480cc10674d5557d16ae0730bbb6da1b884779

**Comment by rtapales** [comment]
Verified.
