### ISSUE TITLE
Primary Theme: Authors

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#123]
http://gettylabs.org/quire/quire_starter_theme_010819/primary/normal/essay/

Example:
'Rose Valland, Chair, Commission fo rate Protection of Works of Art'

Let's go with one color for everything - #666666.

**Comment by mantasandri** [comment]
Should be fixed with https://github.com/gettypubs/quire-starter-theme/commit/424258f965e2e0cdb28302f0fb545dc4b1ba99af - went more programatic route incase user decides to use a darker background.

**Comment by rtapales** [comment]
Verified.
