### ISSUE TITLE
Primary Themes: Entry page

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#124]
http://gettylabs.org/quire/quire_starter_theme_010819/primary/normal/section/2/

- The sliding animation is a little slow and uneven. Can we speed up and ease the animation?
- Page Title/H2: Reduce size to 30px.
- Object metadata table: Reduce font size to 14px.

These might apply to secondary theme as well.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/91e7f7b47781a083e3a6c89b95b767a37021afec

**Comment by rtapales** [comment]
- Sorry, I think it's an h1 header (e.g. '3. Entry') that needs to get reduced from 32px to 30px.
- Also, can we reduce the table copy to 14px?

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/5cda3d6acdb97135dc27d2df6fe60d2a9d996a8c and reuploaded.

**Comment by rtapales** [comment]
Verified.
