### ISSUE TITLE
Primary Theme: Entry (View Collections button)

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#125]
http://gettylabs.org/quire/quire_starter_theme_010819/primary/normal/section/3/

- Match treatment of back button:
- Border and text should be accent color.
- Add a little more top margin.

**Comment by mantasandri** [comment]
Fixed with: https://github.com/gettypubs/quire-starter-theme/commit/91e7f7b47781a083e3a6c89b95b767a37021afec & https://github.com/gettypubs/quire-starter-theme/commit/b3d7a12f9279865183eb2990e06cc2c3adf17e79

**Comment by rtapales** [comment]
Verified.
