### ISSUE TITLE
Primary + Secondary Themes: Dropcap

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#126]
http://gettylabs.org/quire/quire_starter_theme_010819/primary/normal/section/page/

- Remove top margin so it aligns to the top of the first paragraph.
- Should be 4 lines max. 5th line should wrap under drop cap.

**Comment by mantasandri** [comment]
Chrome vs FF issue.  Fixing to resolve on one would break working properly on the other.  Fixed with https://github.com/gettypubs/quire-starter-theme/commit/6fb3e65c09f216a724eea9416f0cc39b9112eaa5
