### ISSUE TITLE
Primary Theme: Bibliography

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#127]
http://gettylabs.org/quire/quire_starter_theme_010819/primary/normal/section-no-landing/bibliography/

Use same treatment as the 'Notes' section at the bottom of the page - Noto Serif as base font and match size.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/ca59a39764b4a065fdd6ceeabca132e038d96421

**Comment by rtapales** [comment]
Verified.
