### ISSUE TITLE
Secondary Theme: Primary Nav

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#129]
Change font to Noto Sans.

**Comment by rtapales** [comment]
Also, can we change the hover color of the text to the accent color. This might mean making the gray background a touch lighter for contrast.

**Comment by rtapales** [comment]
Font looks good but I noticed we lost the background button hover on the primary nav buttons - a departure from the comps but it works, especially for the reverse treatment. Can we add this back? I think I may have a ticket to just tighten the spacing separating the buttons. Let me know if you have any questions.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/091ab2cff666aa3ef919a33c99e898b44204872b and reuploaded for your review.

**Comment by rtapales** [comment]
Sorry to be nitpicky. 

- I think the gray background (on hover) + color accent is not creating enough contrast. Can we try the accent color for the background and white for the button symbols?
- Also can we even out the left + right padding for the back and next buttons. Looks like there's less padding on the side closest to the home button.

**Comment by mantasandri** [comment]
Not a problem, prefer to get it right.

- Done and added with https://github.com/gettypubs/quire-starter-theme/commit/40a0b73f31132b646f0480baf857117fdc3da8b5.  Reuploaded for review.
- Which area are you refer to?  I'm not seeing a padding difference on the home button (both have 1em): 
![image](https://user-images.githubusercontent.com/11049084/52074507-e4e62980-253e-11e9-9e9e-c388d089684c.png)

**Comment by geealbers** [comment]
@mantasandri, I think @rtapales  looking at it in terms of the hover effect which must be the padding on the `a` element?:

<img width="620" alt="screen shot 2019-01-31 at 2 16 23 pm" src="https://user-images.githubusercontent.com/7796401/52089196-dd387c00-2562-11e9-8387-60703beb7413.png">

**Comment by mantasandri** [comment]
Got it, that makes it a bit clearer and I should of fixed it.  Just pushed up https://github.com/gettypubs/quire-starter-theme/commit/5e2416c2548e1dd6c8c3211dbe5d96d331c4eaf3 and reuploaded.  Check it out and let me know how that looks now.

**Comment by geealbers** [comment]
yes, that's better. I might just go a little wider so that the spacing is equal to that around the middle home button

**Comment by mantasandri** [comment]
Done - bumped it up .5em with https://github.com/gettypubs/quire-starter-theme/commit/4e2352ea5564e8a8a8e929e63ab54e2c255e1fff.  Let me know how that looks now.

**Comment by geealbers** [comment]
perfection. thanks!
