### ISSUE TITLE
Secondary Theme: Contents Abstract/Description

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#130]
The symbol used to separate the abstract/description is different from the one used for the Primary Theme. 

[secondary_theme_snippet_separator.txt](https://github.com/gettypubs/quire/files/2788517/secondary_theme_snippet_separator.txt)

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/48ead4d8d3a6300f1a171a347f634615b89bb96e

**Comment by rtapales** [comment]
Verified.
