### ISSUE TITLE
Secondary Theme: Background color

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#131]
Change to white.

**Comment by rtapales** [comment]
You would need to also reduce the margin above the content well and possibly below since you'll have more white space.

http://gettylabs.org/quire/quire_starter_theme_121918/quire_starter_theme_secondary_foreword_page.html

**Comment by mantasandri** [comment]
Was fixed with https://github.com/gettypubs/quire-starter-theme/commit/89d4d9adcc6a0ebce5acb3dec733b0771b2e08b7
