### ISSUE TITLE
Secondary Theme: Section

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#132]
http://gettylabs.org/quire/quire_starter_theme_010819/secondary/normal/section/

Mostly the same comments from the Primary theme. Here's a reference to the font treatment:

http://gettylabs.org/quire/quire_starter_theme_121918/quire_starter_theme_secondary_catalogue_page.html

**Comment by mantasandri** [comment]
Fixed with: https://github.com/gettypubs/quire-starter-theme/commit/a6c1b6b8f6e7598ea998e942cae06adcb3ee7aef

**Comment by rtapales** [comment]
Verified.

**Comment by rtapales** [comment]
- There's a floating arrow. Not sure where this is coming from.
- Also, I noticed that this page is lacking a section title/link like we have in the comp. Any way to show that element?

**Comment by mantasandri** [comment]
The floating arrow links the splash page due to how the menu and pages are structured.  I added in logic to show the page's title if there are no objects found.

I added in a section title & link too.  Reuploaded it as well, let me know how it looks now.

**Comment by rtapales** [comment]
Looks good. Verified.
