### ISSUE TITLE
Secondary Theme: Entry Page

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#133]
http://gettylabs.org/quire/quire_starter_theme_010819/secondary/normal/section/3/

Mostly the same comments as the primary theme:

- Smaller font size for title (30px)
- Smaller font size for the meta data table (14px).
- Make the 'View in Collection' button consistent with our 'Back' button - so ghost treatment with same type treatment and hover.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/91e7f7b47781a083e3a6c89b95b767a37021afec

**Comment by rtapales** [comment]
- Title font still needs to get smaller - 30px.
- Table copy goes down to 14px.

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/5cda3d6acdb97135dc27d2df6fe60d2a9d996a8c and reuploaded.

**Comment by rtapales** [comment]
Verified.
