### ISSUE TITLE
Secondary Theme: Notes

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#134]
Switch font to Noto Sans.

**Comment by mantasandri** [comment]
Fixed with: https://github.com/gettypubs/quire-starter-theme/commit/b873858b0823229c0c75ecc5de4d8a00f23d0173

**Comment by rtapales** [comment]
Sorry, same with Bibliography and any content in the 'notes section'

**Comment by mantasandri** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/1b49c1e01ae56c929ca288c1da31ef197c571b1f
