### ISSUE TITLE
Secondary Theme: Figures

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#135]
http://gettylabs.org/quire/quire_starter_theme_010819/secondary/normal/figures/

Remove top/bottom borders separating figures from main content. You'll have to adjust spacing (decrease top/bottom padding) as a result. See comp for reference.

http://gettylabs.org/quire/quire_starter_theme_121918/quire_starter_theme_secondary_image_sets_A1.html

There are also some comments for the Primary Theme that apply here.

**Comment by mantasandri** [comment]
Config was set to display the figureLabelLocation to below, changed to on-top.  Fixed with: https://github.com/gettypubs/quire-starter-theme/commit/069b412191d9ac5ee87e8dfb5ab3244d9552ea7b & https://github.com/gettypubs/quire-starter-theme/commit/4a305b03ecfcecf4a6d1fc814677c6ebc2124054

**Comment by rtapales** [comment]
Verified.
