### ISSUE TITLE
Quire UI: Primary Navigation

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#136]
- Explore moving hamburger menu to the center and changing the interaction from an expandable menu to an overlay.
- This could mean moving the search button back to the right-hand side and adding a home button/logo on the left.
- Alternatively, we could add a citation button on the right-hand side and possibly a settings menu down the road.

**Comment by geealbers** [comment]
I think we will be pursuing these ideas, but closing this stale issue for now
