### ISSUE TITLE
Primary and Secondary Themes: Updated Cover Image

### ISSUE THREAD

**Issue by rtapales** [gettypubs/quire#137]
[quire_cover_default_012919.zip](https://github.com/gettypubs/quire/files/2809002/quire_cover_default_012919.zip)

Hi Mantas,
Here are 2 versions of the revised cover image:

- Pattern with Embedded background gradient
- Transparent pattern only (background would be done as a CSS horizontal gradient #55F3FF (left value), #0090D4 (right value).

The latter option is a little more work but it might be easier to update in the future.

Ramon

**Comment by mantasandri** [comment]
Applied with https://github.com/gettypubs/quire-starter-theme/commit/e0e873257b8c018e51d93825e797732a55f932b4 and went with 2nd option for better future proofing.

**Comment by rtapales** [comment]
Verified.
