### ISSUE TITLE
Add error messaging on all shortcodes

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#15]
All Quire shortcodes should have highly-visible error messaging built in, in order to give users more comprehensive understanding of why something isn't working. Without this feedback, Hugo will often still build the page, but leave the shortcode in as plaintext, which can be difficult to notice, and difficult to resolve once you do.

Error messages have been incorporated into the `q-figure` and `q-figure-group` shortcodes. An example of which can be seen in the screenshot here:

<img width="979" alt="screen shot 2018-01-26 at 3 57 09 pm" src="https://user-images.githubusercontent.com/7796401/35465536-9f75d4aa-02b1-11e8-86ec-5859fe9ffcd3.png">

**Comment by egardner** [comment]
The logical way to do this would be to define a single `error` partial which accepts a consistent set of parameters like `message` and potentially provides a link to the relevant online documentation for the component in question. This would be much easier to maintain than keeping separate blocks of error handling logic in each short code.

**Comment by geealbers** [comment]
Ha! I thought you left @egardner! 

Agree with that totally. On my first pass trying to build it as a partial, I still needed all the logic and then was passing a lot of text in for the message and such and it was getting pretty messy. The partial kept the HTML markup consistent, but wasn't really cleaning things up in the template as much as I'd hoped. Will definitely give it another shot though.

(ps. sorry for all the notifications as I translate our post-it issues to github issues. 😬)

**Comment by egardner** [comment]
Haha no worries - I’ll mute some of those repos but I’ll keep an eye on Quire stuff and continue to chime in when I have some ideas. 

For the error template, can you have one shortcode inside of another? That would allow you to just place the message inside of the tag as markdown content but that’s probably too simple to be true...

**Comment by geealbers** [comment]
Have [added an error-message.html partial](https://github.com/gettypubs/quire-starter-theme/commit/03b9701113c3cab103108e6dc673e739b7273a67). It helped tidiness to pull the pass through information out as variables at the top the shortcodes rather than passing that information inline. 

Example from the `q-cite` shortcode:

```
{{ $errorMissingReference := dict "shortcode" "q-cite" "message" "The short reference supplied doesn’t match one in the project’s `references.yml` file" "example" "{{< q-cite &#34;Faure 1909&#34; >}}<br /><br />short: &#34;Faure 1909&#34;" }}
```
And then:

```
{{ partial "error-message.html" $errorMissingReference }}
```

Have had to include some HTML markup and entity codes in the examples that are passed through in order to have the proper formatting, but it's not too bad. Error messaging in this way is now implemented in all existing shortcodes except for `q-deepzoom` and `q-map` which are under review for being combined (issue #17), so a note will be added to that item to include error messaging in the final version of that shortcode.
