### ISSUE TITLE
Captions with links are duplicated above figcaption in figure groups

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#164]
When using the `q-figure-group` shortcode, if the figure's caption includes a link of any kind, it is being duplicated and added to the page between the figure and the figcaption along with any text that follows it. 

<img width="932" alt="Screen Shot 2019-03-20 at 12 32 58 PM" src="https://user-images.githubusercontent.com/7796401/54713874-e8446d00-4b0c-11e9-8904-590588b87127.png">

<img width="814" alt="Screen Shot 2019-03-20 at 12 30 52 PM" src="https://user-images.githubusercontent.com/7796401/54713882-ebd7f400-4b0c-11e9-8c27-fd71697f8184.png">

**Comment by naeluh** [comment]
@geealbers I will make a patch for this

**Comment by geealbers** [comment]
Fixed with https://github.com/gettypubs/quire-starter-theme/commit/a6d7356fe598268924ef7ed89d9327ac1523bb66
