### ISSUE TITLE
toggleSearch: TypeError: t is nul

### ISSUE THREAD

**Issue by oncletom** [gettypubs/quire#166]
I cannot trigger a search throughout the documentation as each click on the magnifier icon triggers this error.

<img width="1440" alt="Screenshot 2019-04-03 at 11 10 23" src="https://user-images.githubusercontent.com/138627/55467259-307d8800-5601-11e9-9fce-584751883a73.png">

**Comment by naeluh** [comment]
Hi @oncletom thanks for reporting this. I can't seem to reproduce this. Can you give me more detail about your computer and browser. Thanks!

**Comment by oncletom** [comment]
Right! It works well on the docs homepage. But I face the problem with Firefox 66 (w/ uBlock Origin installed) on https://gettypubs.github.io/quire/guide/fundamentals/. I don't have the problem with Chrome.

---

Oh well, I did a full cache refresh and the problem vanished. Maybe I had an older version of an asset.

Problem solved!
