### ISSUE TITLE
tab/shift tab no longer works

### ISSUE THREAD

**Issue by samyem** [gettypubs/quire#174]
indent using tab keyboard shortcuts no longer works. the focus shifts to the next item instead. also there is no way to do this via mouse/menu and relies solely on keyboard shortcut only.

**Comment by geealbers** [comment]
Thanks for posting this issue, and I'm happy to take a look at it, but could you give me some more information about what you're trying to indent, or what menu you're looking at? I think there's a chance you might have the wrong project. This Quire is a multiformat book publishing tool. https://gettypubs.github.io/quire/
