### ISSUE TITLE
toggleCite() function removed from curent version of theme

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#177]
@naeluh, for some reason, this commit in the starter theme seems to have removed the `toggleCite()` function that @mantasandri had written, and I'm not sure what else it may have removed or changed: [3878cd9](https://github.com/gettypubs/quire-starter-theme/commit/3878cd92df789c9c5d6799cc141aebcbdab90e62#diff-7ae2e702912591bc182bd5996486d506L402). Maybe we had a couple merges that overrode one another and didn't notice?

**Comment by naeluh** [comment]
Hi @geealbers ok sorry about that I think that was an accident and that was it. 

I will create a pull request now.

**Comment by geealbers** [comment]
Closed with [f24321e](https://github.com/gettypubs/quire-starter-theme/commit/f24321e54dc3118092d38c039f10186a5e743272)
