### ISSUE TITLE
What can be added from Bauhaus website work

### ISSUE THREAD

**Issue by naeluh** [gettypubs/quire#178]
This is a list of items from the [bauhaus](https://www.getty.edu/research/exhibitions_events/exhibitions/bauhaus/new_artist/) website that was added outside of quire that in my opinion could be added to quire core:

- drop down navigation at the top
- hero image with caption
- block quote with image

**Comment by mandrijauskas** [comment]
I'd say some of these might be useful
- Sub header nav
- Cite feature at top
- Pullquote
- Collapsable footnotes

And maybe the side nav which points to anchor links for the pages that have them?

**Comment by naeluh** [comment]
Hi @mandrijauskas Ok thanks maybe we can implement these in the next version of quire

**Comment by geealbers** [comment]
Closing as stale
