### ISSUE TITLE
Update EPUB templates and build settings in CLI

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#20]
While we have basic EPUB output working, there are a few remaining items to work in (cover image handling and CSS), as well as some changes that need to be made after the recent update to the content model.

- [x] Update [cover image](https://github.com/gettypubs/quire-cli/blob/f4b6f5846b57d8cd3e31b080f042aeb4076b8cda/lib/epub.js#L66) to pull the one defined in .Site.Data.publication.promo_image
- [x] Update [creators](https://github.com/gettypubs/quire-cli/blob/f4b6f5846b57d8cd3e31b080f042aeb4076b8cda/lib/epub.js#L31) handling to account for new content model. Rather than look for `primary_contributor`, needs to look for `contributor` with a `type: "primary-contributor"`
- [x] Look into adding `contributors` handling for `contributor`s with a `type: "secondary-contributor"`. EPUB uses Dublin Core and so can support "creators" (as the primary) and "contributors" as the secondary group.
- [x] For both `creators` and `contributors`, the name constructor should look for `full_name` first, and if not present use `first_name` and `last_name`. Not sure what to do with the `file_as` value when `full_name` is used, leave it out? 
- [x] Update [description.full](https://github.com/gettypubs/quire-cli/blob/f4b6f5846b57d8cd3e31b080f042aeb4076b8cda/lib/epub.js#L73) to strip out new lines (\n), and any HTML tags. I ran into a problem with this in trying to validate another EPUB.
- [x] Remove [the `templates/epub` directory](https://github.com/gettypubs/quire-cli/tree/master/lib/templates/ebook) and its contents, as these are now being handled through `pe-epub.js`.
- [x] Add handling to pull in an optional `epub.css` file, which would live in the `source/css` directory of the theme as `epub.scss`.

**Comment by geealbers** [comment]
We also need to update the location and name of the resulting EPUB file. Currently, `quire epub` creates the epub and saves it as `test.epub` into the project's root directory. It should instead go into `static/downloads` directory, and to be consistent with the `quire pdf` be named `output.epub`, though ideally both of these would have some more project specific name. The title of the publication perhaps, or just the name of the project directory.

`quire epub` also outputs a new directory with a UUID, which comprises an un-zipped copy of the epub. This is an output of `pe-epub` and should be suppressed or eliminated somehow.

**Comment by geealbers** [comment]
@fchasen can we close this issue? were there any new/additional issues related to the epub that we need to add to the list in place of this one?

**Comment by fchasen** [comment]
I think this should be good for now
