### ISSUE TITLE
Homepage: Determine placeholder for "Intro Video"

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#221]
If we don't have a placeholder in mind, let's remove this illustration/link.

**Comment by Erin-Cecele** [comment]
FYI - I added an older (and very long) demo as a temporary placeholder.

**Comment by geealbers** [comment]
Yeah, we just don't have anything like what I think we'd want here. I removed it and rearranged some of the other feature cards to balance.

Done with da0aab8
