### ISSUE TITLE
Homepage: Determine footer content and style 

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#225]
Maybe mirror the headers + social media handles, github link, code of conduct (?)

**Comment by geealbers** [comment]
Done with 879f50e

For now, I just added a very simple, very short, regular style list of links to GitHub, our about page, and a Contact link that mails to @Erin-Cecele. Though I think we should ask Getty Digital about getting a quire@getty.edu email address to use instead.

I also mirrored these same links in the footer of the sidebar menu, which also includes Getty-required Privacy Policy and Terms of Use links.
