### ISSUE TITLE
Print out Hugo error messages when running `quire preview` command

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#23]
Currently, when running `quire preview` any Hugo error messages are suppressed. It would be preferable to show them to the user, as even a small change in any of the templates can break the Hugo build process, and for now users have no way of tracking down the issue except by stopping Quire and running `hugo server` instead.

**Comment by egardner** [comment]
This is easy to change. Node's Child Process api (the module that handles running other processes like shell commands inside a program) lets you specify [some options](https://nodejs.org/api/child_process.html#child_process_options_stdio) for how to handle output. The behavior you want here can be passing in the options value `{stdio: 'inherit'}` when you are spinning up the relevant child process.

If you look at QuireCLI's [`preview()` method](https://github.com/gettypubs/quire-cli/blob/master/lib/project.js#L100-L101), you can see that the `webpack` process has `stdio: inherit` set while the `hugo` process does not.  Changing the second line there to:

```js
execFile(hugo, ['server', '--config=config.yml,config.dev.yml'], { stdio: 'inherit' })
```

Will do what you want. The same change would need to be made to `build`, `epub`, `pdf`, and any other methods where you wanted the same behavior.

One idea I was considering but never had a chance to implement was allowing the user to specify if they wanted all this output or not (I could see some people getting confused by it, though when things go wrong it is helpful). A lot of CLI utilities support a `--verbose` flag that changes the amount of data that is spit out for the user to see, and the same thing would certainly be possible here. In that case, the `stdio` option above would be set to a different value depending on whether or not the program was running in "verbose" mode.
