### ISSUE TITLE
About: Review/Copy Edit "History" page

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#233]
- [x] Add/revise milestones 
- [x] Suggest better videos and other multimedia content

**Comment by geealbers** [comment]
Done with 34202e2

I removed the old 2013 video, and I wish the 2017 one wasn't audio-only, but I doubt people will click through anyway and the fact that it's simply there and a thing is good enough for the messaging we want to convey.

For edits to the timeline, I made a bunch, but particularly focused on naming everyone involved at the Getty (like you had Eric and I), and also trying to introduce a couple more items that names our community members as well.
