### ISSUE TITLE
Community: Make suggestions for links on "Join Us" page

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#239]
What should the following pages link to:

- Ambassador page (should we have a placeholder landing page? If yes, I will make new issue)
- Submit your work (can we have a form?)
- Contribute to code (should we link to a repository?)
- Add to Documentation (I'm thinking we create a list in Github of sections that need work - if yes, I will make new issue)

**Comment by geealbers** [comment]
Done with 491d6f9

I ended up creating a "coming-soon" action button variation (that looks like a grayed out button) and applied that to the ambassador program and the forum. I also tried new wording on all the button to eliminate repetition with the headings I added. Obviously feel free to further edit them.
