### ISSUE TITLE
Community & Homepage: Add links to publication websites on "User Showcase" page

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#240]
Make it so that when clicking publication images it links directly to respective websites. Is this possible?

**Comment by geealbers** [comment]
Currently working on this, see PR #287 

Some TODOs for myself:

- [ ] Adjust grid for mobile
- [ ] Fix SVG icon clickability bug
- [ ] Add alt text field for image
- [ ] Determine image size ratio and document ways to ensure we maintain it going forward

**Comment by Erin-Cecele** [comment]
FWIW, I tried to keep dimensions for all publication images at 1200 x 668 (give or take a teeny tiny bit) and 72dpi. 

I couldn't find an app or anything that helps consistently maintain size when taking screenshots but maybe Audrey could help with this research?

**Comment by geealbers** [comment]
Done with 8e0ad9e.

For the homepage, I expanded the capabilities of the q-showcase code so that I could use that instead of the q-figure-group shortcode. So now, with q-showcase, you can include a list of IDs and only display those, rather than displaying all the projects.
