### ISSUE TITLE
Documentation: Review/Edit "For Developers" section as placeholder

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#243]
Is this suitable for now? 

- [x] Update BlackFriday information 
- [x] Check for any other inconsistencies 
- [x] Replace image where is says "Proyect Folder"
- [x] Check all links

**Comment by geealbers** [comment]
I also want to first take a design pass at it and see if I can make it a little easier to parse

**Comment by geealbers** [comment]
Closed with pr #299
