### ISSUE TITLE
Learn: Review "Helpful Resources" page and suggest structure/content alternatives

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#245]

**Comment by geealbers** [comment]
I made additions to the Resources page and had some thoughts about the Learn section overall.

- Move the Glossary here, which was probably your intention but I initially stuck it in Documentation
- Eliminate the Tools page, I don't think it's doing anything useful for us
- Consider adding Articles into the mix, and making them accessible through a joint Videos & Articles page, and link to the GitHub one through that

On the Articles, I've honestly lost track of some of our past conversations about this, so you may have already considered it, but I'm a little nervous about our ability to crank out a significant number of videos. So, I though we could mix it up and have videos and written articles together, giving us a wider pipeline to feed into. Basically, I feel like I could write a couple articles on targeted subjects a lot faster that producing a couple videos at this point.

**Comment by Erin-Cecele** [comment]
Two out of the three bullets have been done. 

As for Articles, I feel like we could actually add some to the site now (GitHub, Open Source, How it Works, and I've typed up directions for using command-line.)  I can create an "Articles & Videos" and to prevent it from being too empty, we could add past conference presentations as videos (similar to what Arches has done: https://www.archesproject.org/videos/). I'm also hoping to record a sample video tutorial for command-line soon. 

Other Article ideas include various workflows, first commit/contribution, and more tutorial topics. 

This is also a complete aside but would we ever want to include press coverage anywhere on the site? Again, somewhat inspired by Arches: https://www.archesproject.org/materials/. I guess if anything significant comes out we can just add it as an item in the news section?

**Comment by geealbers** [comment]
Yes, sounds good. Why don't you go ahead and create an Articles & Videos page.

And yes, I think for now, we could list press coverage in our News section. And when the deluge of coverage becomes overwhelming, we can create a separate page for it. :)

**Comment by Erin-Cecele** [comment]
Hahaha!  

Ok great! I'm going to close this issue and create a new issue for Articles & Videos so we don't get confused.
