### ISSUE TITLE
Documentation: Add text to Getting Started (Erin)

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#246]
Help make this a landing page for the Documentation.

- [ ] Include information CLI
- [ ] Include information on Install 
- [ ] Potentially reorder pages to mirror these adjustments

**Comment by geealbers** [comment]
Are these still changes you'll want to make now that this page doesn't need to be a landing page?

**Comment by Erin-Cecele** [comment]
Ah, I believe that solves the problem!
