### ISSUE TITLE
General: Website Edits 

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#250]
- [ ]  Keep an eye out for subjective words/phrases like " it's easy", "simply" or "just".
- [ ] Keep an eye out for excessive "!" In some places the emphasis makes sense but in other places, it might be too much.
- [ ] Check links on pages and fix broken links. If you come to me with some examples, I can walk you through fixing them.

**Comment by Erin-Cecele** [comment]
@audreywarne 

Here are the pages to focus on for this issue. I honestly think this will be very quick. If you catch any other errors beyond subjective language and ! please feel free to make necessary corrections (which you have already done for history/how it works/what is quire). 

- [ ] Homepage (cover.md)
- [ ] What Is Quire (about/quire.md)*
- [ ] How it Works (about/how-it-works.md)*
- [ ] Open Source (about/open-source.md)
- [ ] History (about/history.md)*
- [ ] Join Us (community/join-us.md)
- [ ] Implementation Considerations (documentation/implementation.md)
- [ ] Tutorial (learn/tutorial.md)

**Comment by audreywarne** [comment]
@Erin-Cecele I looked over the pages and made a few edits under the branch audrey-issue-250.
