### ISSUE TITLE
Community: Create Submission Form?

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#251]
Can we create a submission form to be used in User Showcase & Join Us (submit your work) or should it just be linked to an email address?

**Comment by geealbers** [comment]
@Erin-Cecele, I took a first stab at the form if you want to go in there and edit away! For now it's just in the top level of our Google Drive Quire folder

https://docs.google.com/forms/d/e/1FAIpQLSeJWyTA9OUjdQnw8JsmJudJuIzGRAzTeTL7BWr_L6u6C67bCA/viewform?usp=sf_link

**Comment by Erin-Cecele** [comment]
Great! I love it. Only have a few minor tweaks I want to make but it looks great.

**Comment by geealbers** [comment]
Assigning this to you @Erin-Cecele just as a reminder to make whatever tweaks you'd like

**Comment by Erin-Cecele** [comment]
Done!
