### ISSUE TITLE
Issue with opening links on website 

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#269]
Clicking links on website take you away from website rather than open new external pages.

**Comment by Erin-Cecele** [comment]
@geealbers I saw you offered Sarah Wambold a few solutions for target blanks. One involved a newer version of Hugo. 

Another option seemed to be writing these links out in HTML instead of markdown. This is the example you gave.  <a href="https://www.patreon.com/posts/36579502" target=_blank">https://www.patreon.com/posts/36579502</a>.

How best to proceed for Quire?

**Comment by geealbers** [comment]
Closed with 42ae10a
