### ISSUE TITLE
"Q-Figure" and "Q-Class Box Tip" are not working when used together

### ISSUE THREAD

**Issue by Erin-Cecele** [gettypubs/quire#281]
The combination of a box tip and a q-figure shortcode is not working.

**In the markdown, this:**

`{{< q-class "box tip" >}}`

-You can also type `cd` and a space in your shell and then drag and drop the Quire directory icon into it. This will copy the full file path.

`{{< q-figure id="command-line-drag-and-drop" >}}`

`{{< /q-class >}}`

**Results in this:** 

<img width="652" alt="Screen Shot 2020-09-28 at 3 52 32 PM" src="https://user-images.githubusercontent.com/62075223/94493862-a042e380-01a2-11eb-94ed-9b92982d3b76.png">

**However, if you remove the q-figure code from the box tip and place it after `{{< /q-class >}}` then it works just fine, but it looks really messy.** 

<img width="678" alt="Screen Shot 2020-09-28 at 3 54 24 PM" src="https://user-images.githubusercontent.com/62075223/94493976-e39d5200-01a2-11eb-824c-172a6ef8e316.png">

**For reference, here is how it *currently* looks in our documentation:** 

<img width="657" alt="Screen Shot 2020-09-28 at 3 55 00 PM" src="https://user-images.githubusercontent.com/62075223/94494006-f9127c00-01a2-11eb-8728-b53cb3d1bd3a.png">

**Comment by geealbers** [comment]
Yes, this happened when Hugo switched to Goldmark as a markdown processor. It seems we can't have shortcodes inside another shortcode like that anymore. The solution that should work is to use the html version `<div class="box tip">        </div>` in place of `{{< q-class "box tip" >}}        {{< /q-class >}}`

**Comment by Erin-Cecele** [comment]
Ah hah!! Thank you! 

I ended up doing this:

`<div class="box tip">`

- You can also type `cd` and a space in your shell and then drag and drop the Quire directory icon into it. This will copy the full file path.

`![Drag-and-drop](/img/screenshots/command-line-drag-and-drop.gif)`

`</div>`

To prevent the weird lines and caption section that gets included with a regular q-figure image.
