### ISSUE TITLE
About: Copyedit recently updated pages

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#284]
Working off a new branch from the `theme-update-v18` branch, please give the below pages from the About section a look for any errors, nonsensical sentences/words and the like.

@Erin-Cecele do you have any tips for @audreywarne on what else she should be looking for when copyediting these pages?

- [x] /about/how-it-works.md
- [x] /about/roadmap.md
- [x] /about/quire.md
- [x] /about/history.md

Audrey, look too for any opportunity to link to other sections of the site, or to add pop-up glossary definitions. To add a definition, use the q-def shortcode, that points to an entry in the data/glossary.yml file. You can see how they work by looking around the pages of the site. Here's an example pop-up code for "command-line shell":

```
Open your {{< q-def "command-line shell" >}} and copy and paste the text below
```

**Comment by Erin-Cecele** [comment]
Yes! @audreywarne, per issue #250, it would be great if you could assist with the following as you copy edit:

- [ ] Keep an eye out for subjective words/phrases like " it's easy", "simply" or "just". 
- [ ] Keep an eye out for excessive "!" In some places the emphasis makes sense but in other places, it might be too much.

Here are some additional things we'd love your assistance with while copy-editing: 
 
- [ ]  Check links on pages and fix broken links. If you come to me with some examples, I can walk you through fixing them.  
- [ ] Remove gerunds from documentation section / subsection headers. For example, it should be "Output & Deploy Your Site". The goal is to make navigation less wordy and convoluted. 

Let me know if you have questions,

Erin

**Comment by audreywarne** [comment]
Okay, I think I made the appropriate copy edits (and tried to add in some more definitions).

The 'notable challenges remained' hyperlink on the history page (under 2017) is broken ("page not found").

**Comment by Erin-Cecele** [comment]
I noticed that too @audreywarne. Please replace the broken link with the following: https://www.getty.edu/publications/osci-report//remaining-challenges/.

**Comment by audreywarne** [comment]
I do have a comment about the links—would it be possible to have them open in a new tab? With all of the links it's easy to get pulled away from the actual quire website.

**Comment by Erin-Cecele** [comment]
Great observation @audreywarne. That is something Greg and I just discussed. We are working on it! 

Also, I realize in retrospect that the list of action items I posted 30 mins ago applies to the full website and not just the pages that Greg requested reviewing. I'm going to delete the comment above and edit issue #250 which will then be assigned to you. And please feel free to check the boxes for the action items as you complete them.

**Comment by geealbers** [comment]
@Erin-Cecele, Audrey's changes are in this commit: https://github.com/gettypubs/quire/commit/46cb4a015d8480ac3f306089fce3107cb61e710b

Could you review when you have a chance and let her know if you have any questions?

**Comment by Erin-Cecele** [comment]
@audreywarne you did a great job cleaning up / simplifying language. Thank you!! 

Two small things to fix:

- On line 43 of the History page, please remove the link to OSCI. It is already mentioned up above.
- Similarly, when using the q-def shortcode, only use it the first time a word is mentioned and with every instance of that word. I mostly noticed that with "static site generator" in the How It Works section. 

Otherwise, these edits look great!
