### ISSUE TITLE
Create evaluation protocol for beta testers

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#32]
I've got a basic [outline of our beta testing process](https://github.com/gettypubs/quire/wiki/Guidelines-for-Quire-Beta-Testing) in the wiki. As you'll see, once approved for the beta, testers will be asked to get started on their own first. We'll then do a evaluation of their experience up to that point, and then have a call with them to talk more specifically about their project and next steps. What we need to do is come up with a specific evaluation system for this first phase, after they've tried it out on their own. The evaluation might be an online survey form, an interview or conversation, or both, or something else altogether.

Here are some initial possible questions I jotted down quite some time ago:

- On a scale of 1 to 5, 1 being the easiest, how difficult was the process?
- Do you feel it worked as expected?
- How many times did you consult the documentation?
- Did you consult with anyone else or do any google searching?
- How would you describe the process to someone who was going to be doing it for the first time themselves?

I like the last one, but not sure how useful they all otherwise are. I think generally the questions we ask should be related to the steps taken (or better, skills learned) during the steps in the Getting Started chapter. The idea is to test where users run into trouble on their own, what they learn initially about Quire, and what questions they have in taking the next steps.

**Comment by swambold1** [comment]
@geealbers I've reworked the questions and added some notes. Let me know if we're on the same page.

https://docs.google.com/document/d/1C01rF9EKJPK_7J9tVhhGu4JFN-yss-aMx8CIEaOFVi4/edit#

**Comment by geealbers** [comment]
Closing as stale. With @Erin-Cecele onboard though, we will be doing much more communicating and evaluating with our beta users
