### ISSUE TITLE
Is it possible to install Linux?

### ISSUE THREAD

**Issue by halbayrak75** [gettypubs/quire#34]
Mac and PC installation documents are written.

So can I install Linux (Like ubuntu)?

Thank you

**Comment by geealbers** [comment]
Hi. We haven't done any testing on Linux at all, and honestly it's outside my experience. But it should at least be feasible. @egardner, can you weigh in?

**Comment by egardner** [comment]
If anything, Linux support should be better than windows. My Ubuntu laptop is not currently working but I was definitely able to run Quire at an earlier point in its development.

@halbayrak75 I would encourage you to try installing on Ubuntu and letting us know what happens. You will need to install NodeJS from the OS package manager. This may give you an older version of node (like v4) but I think that will be sufficient. You could always install a more recent version of node from a third-party repository if the default version of Node is not enough.

- `sudo apt-get update`
- `sudo apt-get install nodejs`

On Linux, you should be able to use the full range of Quire commands (`quire preview`, `quire build`, etc). If you can get things running please report back with your results.
