### ISSUE TITLE
Additions to About page

### ISSUE THREAD

**Issue by mbelhu** [gettypubs/quire#4]
Github recommends this link as further reading to create good _readme_ files: https://open-source-guide.18f.gov/making-readmes-readable/

From the questions they suggest to answer in the _readme_ file, these would be the ones we'd need to address:

**Who uses Quire?** 
**What is Quire’s goal?**
**How can you (or your institution) benefit from using Quire?**

**Comment by geealbers** [comment]
Implemented in PR #79.
