### ISSUE TITLE
Anchor links don't behave as expected

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#41]
Anchor links going to other pages and written in Markdown (such as `[note 5](../catalogue/1/#fnref:5)`) will go to the page, but not scroll to the appropriate anchor position. Similarly, the browser back button will change the URI in the address bar, but have no effect on the page position. Presumable both issues are related to Quire’s use of smoothState.js.

**Comment by fchasen** [comment]
Seems to be a few things happening with this issue:

1) jQuery [doesn't like `:` in ids](https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/) so it will need to be escaped (`\\`) like `fnref\\:5`

2) Hugo won't allow passing the escapes in, so the link will need to be html like 
`<a href="../catalogue/1/#fnref\\:5">note 5</a>`

3) `.quire-page` is the only part of the document that scrolls but the smoothState `scrollTo` function only scrolls the entire html document, so nothing is moved.

**Comment by geealbers** [comment]
Oy. Not thrilled about users needing to write links like that in HTML (specifically when linking to footnotes in other pages) and also having to do so using an escape character. That's a lot to document and explain for a very specific use case. And this is about using jQuery overall, or just with smoothState? If the later, maybe worth looking for an alternative to smoothState?

**Comment by fchasen** [comment]
It is both, but thankfully the new version of smoothState lets you turn off the scrolling so hopefully we can just handle finding the correct element and scrolling the right area ourselves.

**Comment by fchasen** [comment]
Eric had already added a function to deal with escaping the ID's in the Roman Mosaics project that might be worth adding to the starter: https://github.com/gettypubs/romanmosaics/blob/master/source/assets/javascripts/ui.js.erb#L3
