### ISSUE TITLE
Add MOBI output

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#51]
`.mobi` is the e-book file format for Amazon. A MOBI file can be created directly from the `content.opf` file of an EPUB, using Amazon's free (but not open source) [KindleGen](https://www.amazon.com/kindleformat/kindlegen) command line tool. We need to find a solution for Quire. After an initial failed search for open source solutions, I'm asking around the community as well, and will post back here. Otherwise, the quickest/dirtiest implementation might be to treat KindleGen like we do PrinceXML and require that users download it on their own so that Quire can then use it, though adding to the install process is not ideal. Thoughts?

**Comment by naeluh** [comment]
Hi @geealbers hope you are having a good day!

I have the new implementation working with pandoc for Epub and KindleGen. 

Do you want these to be separate commands or work from the same command ?

Let me know. 

Thanks!

Nick

**Comment by naeluh** [comment]
@geealbers ok cool that works for me.
