### ISSUE TITLE
Add Photoswipe or similar library for image viewing

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#52]
In [past publications](https://github.com/gettypubs/artistryinbronze/commit/377fbf96df8cf8c8f483d4fd46471dd13ce1fb7b), we've used [Photoswipe](http://photoswipe.com/) to allow figure images to be opened in a lightbox modal at their full size. Photoswipe is nice because it has no dependencies, and also includes image-to-image navigation, the option to include the figure caption and credit, and zooming and full-screen controls. However, we're open to other solutions if one makes sense, though the functionality should largely stay the same.

**Comment by naeluh** [comment]
I found this implmentation of photoswipe with video embed?

https://github.com/dimsemenov/PhotoSwipe/issues/651#issuecomment-350471585

Maybe this will work?
