### ISSUE TITLE
Document dependencies

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#56]
The dependencies in `quire-cli` and `quire-starter-theme` should be documented. Each should include the basic description of the dependency and then a specific statement as to why we're using it and what it does. I'm not sure if there's a best practice for this, but I imagine it could all just be in a table in a page of the docs. Thoughts?

**Comment by geealbers** [comment]
See also issue #55

**Comment by naeluh** [comment]
Hi @geealbers! I added this pull request https://github.com/gettypubs/quire/pull/74 if this works I think we are good to close this. 

Let me know if you have any questions or if I can clarify in any way.

Thanks!
