### ISSUE TITLE
Bring Hugo up to current version

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#58]
When installed through the CLI, Hugo is currently [locked to version v0.31](https://github.com/gettypubs/quire-cli/commit/17de696c2fe0e6890f9ee19d7d0ae9a081a69cc1) in Quire. This is due mostly to [the change in v0.32 that introduced "page bundles"](https://gohugo.io/about/new-in-032/) to the Hugo content model, and that fundamentally changed the way Hugo handles `index.md` files. However, at this time Hugo is on v0.41, and we need to work to bring Quire up to support that most recent version. We should also then determine and document a process for updating Hugo support as new versions are released.

**Comment by bep** [comment]
Let me know if you have any questions -- the side-effects of the `index.md` change was unfortunate, but we discussed it for a long time and it was the obvious identifer to use for that purpose.

**Comment by geealbers** [comment]
Very much appreciated @bep, thanks!

**Comment by naeluh** [comment]
@geealbers It looks as though hugo-bin is at 0.42 https://github.com/fenneclab/hugo-bin/issues/55

I updated hugo-bin 0.29 so I think we are at 0.42.1 and the code is working. 

Was there any other items to remedy in this issue?

**Comment by geealbers** [comment]
@naeluh yes, that was it, I'll close the issue
