### ISSUE TITLE
Quire preview command on Mac terminal generates error; preview fails

### ISSUE THREAD

**Issue by sarakaustin** [gettypubs/quire#78]
Have updated quire-cli (0.1.0.alpha.13), and we all get this error when running quire preview--at home on Mac running Sierra and at work running Yosemite. If you go to localhost:1313 after this you get an "unable to connect" error.

[MacBook:~] ska% cd gail-oxford
[MacBook:~/gail-oxford] ska% quire preview
Launching preview server
Navigate to http://localhost:1313 to see your changes.
Press Control+C or type "quire stop" to stop the preview.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/.bin/webpack ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
[MacBook:~/gail-oxford] ska%

**Comment by naeluh** [comment]
Hi @sarakaustin did you update an existing install of quire? 

If so you may need to reinstall the dependencies. 

What version of npm and node do you have installed?

you can run `npm -v` and `node -v` to get this info.   

Let me know thanks!

**Comment by sarakaustin** [comment]
Hi Nick,

Thanks for the suggestion. I did update quire after getting this error; I will try updating the dependencies as well. Will get back to you.

Sara

---------------------------------
Sara K Austin
Editor-in-Chief
Huntington Library Quarterly
1151 Oxford Road
San Marino, CA 91108
626-405-2138

HLQ site at University of Pennsylvania Press<https://hlq.pennpress.org/home/>
Subscribe to quarterly HLQ table-of-contents alerts<http://eepurl.com/b2TS8z>

**Comment by naeluh** [comment]
Hi Sara, 

Ok let me know if that works.

Also here is what I would do.

```
cd quire-cli

rm -rf node_modules/ 

npm uninstall -g

npm install -g
```

Let me know if that works or if you have any questions.

Thanks!

Nick

**Comment by sarakaustin** [comment]
Nick,

Thank you! This worked on the work computer (yes, older versions for both). npm not only tells you your version number but also tells you the current version and provides the command to update when you enter in the -v command, which is a nice touch; node just prints the current version. Didn’t get a chance at home yesterday, but will try tonight.

Maybe this should be documented for troubleshooting? Let me know if I can help.

Sara

---------------------------------
Sara K Austin
Editor-in-Chief
Huntington Library Quarterly
1151 Oxford Road
San Marino, CA 91108
626-405-2138

HLQ site at University of Pennsylvania Press<https://hlq.pennpress.org/home/>
Subscribe to quarterly HLQ table-of-contents alerts<http://eepurl.com/b2TS8z>

**Comment by sarakaustin** [comment]
Hi Nick,

Unfortunately this sequence did not work on home computer. npm and node dependencies up to date, same error. Here's what happened:

[MacBook:~] ska% cd quire-cli
[MacBook:~/quire-cli] ska% rm -rf node_modules/
[MacBook:~/quire-cli] ska% npm uninstall -g
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
removed 1 package in 66.636s
[MacBook:~/quire-cli] ska% npm install -g
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated deflate-crc32-stream@0.1.2: module has been merged into crc32-stream
/usr/local/bin/quire -> /usr/local/lib/node_modules/quire-cli/index.js

> fsevents@1.2.4 install /Users/ska/quire-cli/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ska/quire-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> mmmagic@0.5.0 install /Users/ska/quire-cli/node_modules/mmmagic
> node-gyp rebuild

  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/der.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/encoding.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fsmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/funcs.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/is_tar.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/magic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/print.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readcdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readelf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/softmagic.o
  LIBTOOL-STATIC Release/magic.a
  CXX(target) Release/obj.target/magic/src/binding.o
../src/binding.cc:274:26: warning: 'Call' is deprecated
      [-Wdeprecated-declarations]
        baton->callback->Call(1, argv);
                         ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/binding.cc:321:26: warning: 'Call' is deprecated
      [-Wdeprecated-declarations]
        baton->callback->Call(2, argv);
                         ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
  SOLINK_MODULE(target) Release/magic.node

> hugo-bin@0.29.0 postinstall /Users/ska/quire-cli/node_modules/hugo-bin
> del-cli vendor && node lib/install

  ✔ Hugo binary is installed successfully
+ quire-cli@0.1.0
added 785 packages from 448 contributors in 79.65s
[MacBook:~/quire-cli] ska% cd
[MacBook:~] ska% cd gail-oxford
[MacBook:~/gail-oxford] ska% quire preview
Launching preview server
Navigate to http://localhost:1313 to see your changes.
Press Control+C or type "quire stop" to stop the preview.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/.bin/webpack ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
[MacBook:~/gail-oxford] ska% npm -v
6.2.0
[MacBook:~/gail-oxford] ska% node -v
v8.11.3
[MacBook:~/gail-oxford] ska%




Sara K. Austin
Editor-in-Chief
Huntington Library Quarterly
The Huntington Library, Art Collections, and Botanical Gardens
1151 Oxford Road
San Marino, CA 91108
626-405-2138
saustin@huntington.org

Subscribe to quarterly table-of-contents alerts for the HLQ: <http://eepurl.com/dv3faD> http://eepurl.com/dv3tRf


________________________________

**Comment by naeluh** [comment]
Hi Sara, 

Ok sorry that is giving you trouble. 

That error would happen if webpack is missing can you run 
```
cd quire-cli
npm install -g 
```
again and then from your project folder run 

```
cd gail-oxford
quire install
```

then see if that fixes the issue

let me know if you have any questions or if I can clarify in any way.

Thanks!

Nick

**Comment by sarakaustin** [comment]
Thanks, I’ll give this a shot tonight.

Sara

---------------------------------
Sara K Austin
Editor-in-Chief
Huntington Library Quarterly
1151 Oxford Road
San Marino, CA 91108
626-405-2138

HLQ site at University of Pennsylvania Press<https://hlq.pennpress.org/home/>
Subscribe to quarterly HLQ table-of-contents alerts<http://eepurl.com/b2TS8z>

**Comment by sarakaustin** [comment]
Nick,


Thank you, that worked. I'll tell my colleague, who was getting the same error.


Sara


Sara K. Austin
Editor-in-Chief
Huntington Library Quarterly
The Huntington Library, Art Collections, and Botanical Gardens
1151 Oxford Road
San Marino, CA 91108
626-405-2138
saustin@huntington.org

Subscribe to quarterly table-of-contents alerts for the HLQ: <http://eepurl.com/dv3faD> http://eepurl.com/dv3tRf


________________________________

**Comment by naeluh** [comment]
HI Sara,

Let me know if you run into anything else.

I think I am going to add some documentation about the update process or make it a command that comes with quire when a new release has been posted. 

thanks!

Nick

**Comment by sarakaustin** [comment]
Nick,

Many thanks for your prompt help with this. I hope my challenges will help others!

Sara

---------------------------------
Sara K Austin
Editor-in-Chief
Huntington Library Quarterly
1151 Oxford Road
San Marino, CA 91108
626-405-2138

HLQ site at University of Pennsylvania Press<https://hlq.pennpress.org/home/>
Subscribe to quarterly HLQ table-of-contents alerts<http://eepurl.com/b2TS8z>
