### ISSUE TITLE
Add Next/Previous keyboard navigation

### ISSUE THREAD

**Issue by geealbers** [gettypubs/quire#9]
As in past publications, the right and left keyboard arrows should take you to the next and previous pages respectively.

**Comment by geealbers** [comment]
We had this working in previous projects. For reference:

- https://github.com/gettypubs/keepitmoving/blob/master/themes/quire-prototype-starter-theme/source/js/ui.js#L110
- https://github.com/gettypubs/romanmosaics/blob/master/source/assets/javascripts/ui.js.erb#L43

**Comment by egardner** [comment]
I’m about to get on the road but yes, this functionality should be easy to add back in. Maybe the question going forward is how JavaScript should be organized in the default templates: some guidelines for developers could be useful here. 

Previously the way I handled this was to create a master ‘UI’ class that is instantiated each time a new page loads. The UI instance would handle things like setting up handlers for keyboard events in addition to navigation, search, and whatever else is going on.

In this approach the ‘application.js’ file can be kept more minimal and is mainly concerned with setting up the UI object once the page is ready (along with other top-level features like smoothstate if you are using it). Other functionality can live inside named methods of the UI class in a separate file for clarity.

**Comment by geealbers** [comment]
See also Issue #40, regarding touch swiping
