### ISSUE TITLE
Customize style of docs publication

### ISSUE THREAD

**Issue by mbelhu** [gettypubs/quire#90]
Additional style customization is needed for the following elements:

- [x] Text column width is too narrow and should be also responsive
![screen shot 2018-08-31 at 2 36 34 pm](https://user-images.githubusercontent.com/17339959/44936888-68e77b80-ad2b-11e8-8877-b6d75841f647.png)

- [x] Make the top of the page navbar a fixed one

- [x] Add a fixed side TOC menu 

- [x] Add side TOC menu for each page sections/headings

- [x] Irregular tables width
![screen shot 2018-08-31 at 1 37 58 pm](https://user-images.githubusercontent.com/17339959/44935636-65052a80-ad26-11e8-812b-942c66563a33.png)

- [x] Syntax highlighting 
If the starter theme color scheme changes the syntax may as well be changed.  Current `pygmentsStyle`  is "monokailight". Other nice options were "rainbow_dash" and "colourful".

- [x] Color for warning notes boxes
If the color scheme for the theme and screenshots labels changes, a brighter color for the boxes would look nice. See also issue #47 

- [x] Add icon to warning notes boxes
See comment on issue #47

- [x] hover over links in warning notes boxes. 
The link background is always white when you hover over links in the boxes. 
![screen shot 2018-08-31 at 2 13 40 pm](https://user-images.githubusercontent.com/17339959/44936706-a7c90180-ad2a-11e8-88c8-c3b6e0956f51.png)

**Comment by geealbers** [comment]
check it out @mbelhu! https://gettypubs.github.io/quire
