### ISSUE TITLE
Display of links in glossary pop-ups

### ISSUE THREAD

**Issue by mbelhu** [gettypubs/quire#92]
Change styling of glossary pop-ups so links are wrapped and clickable.
The screenshot shows the link wrapping issue:
![screen shot 2018-09-05 at 3 52 49 pm](https://user-images.githubusercontent.com/17339959/45125693-8306cc80-b124-11e8-91e4-17a2e8fdf3a5.png)

**Comment by geealbers** [comment]
Fixed with 7e99ddd
