### ISSUE TITLE
Text Highlighting

### ISSUE THREAD

**Issue by cassi** [gettypubs/quire#94]
I started a small personal Quire project, which is centered around a collaborative annotation experience on the web (using Hypothes.is for the annotations).  I quickly found that Quire, by default, prohibits text highlighting by the user, and to work around this I had to do some hot-fixes to force overriding of that setting.

While I can see many situations in which publishers using Quire would not want to allow users to highlight/copy the text, I imagine there are likely to be others who, like me, want to allow that behavior.  It seems as though this decision -- _to highlight or not to highlight?_ -- should be left to the project creators to decide, and set by another variable in the config files.

**Comment by naeluh** [comment]
Hi @cassi Thanks for the notes!! To get this to work did you modify the scss or did you have to modify the the Javascript also?

**Comment by annotating-antonia** [comment]
@naeluh I ended up having to do both.  I started out just trying to override it in the `custom.css` but when that didn't work, I updated the scss as well.  That also didn't do the job, so I changed the JS too, and finally that did the trick.

**Comment by cassi** [comment]
@naeluh I ended up having to do both. I started out just trying to override it in the custom.css but when that didn't work, I updated the scss as well. That also didn't do the job, so I changed the JS too, and finally that did the trick.

**Comment by naeluh** [comment]
@cassi ok sounds good thanks! I will take a look at your commits and see what you modified. If what you did works I can look at including the modifications in a future release. I will let you know if I have any questions. Thanks!

**Comment by geealbers** [comment]
We've fixed this on the newest release so users can select text by default. (The only thing that makes sense when we're talking about primarily open access publications.) Thanks for bringing this to our attention @cassi! 

Closing the issue.
