### ISSUE TITLE
Error building site: logged 2 error(s) -- Preview Issue

### ISSUE THREAD

**Issue by beaaic** [gettypubs/quire#96]
I am getting following errors with the quire preview -v command line and can't figure out where the error exactly occurs. Is it something with the single catalogue pages maybe?

--
Building sites … 
ERROR 2018/09/24 10:00:39 Error while rendering "page" in "catalogue/": template: contents/single.html:22:16: executing "main" at <partial "contents-li...>: error calling partial: template: partials/contents-list.html:128:21: executing "contents-item-toc" at <first 1 .figure>: error calling first: can't iterate over map[string]interface {}

ERROR 2018/09/24 10:00:39 Error while rendering "page" in "catalogue/": template: entry/single.html:36:16: executing "main" at <.id>: can't evaluate field id in type interface {}

Total in 180 ms

Error: Error building site: logged 2 error(s)
--

**Comment by naeluh** [comment]
Hi @beaaic can you give me access to your code? This seems to be an issue with hugo. Thanks!

**Comment by beaaic** [comment]
Hi @naeluh 
Thank you! It's working again. There was an issue with my custom CSS sheet. I think that's what it was.
